// The chapters of the atlas. Chapter = curated path: an ordered walk through
// the grooves of one lineage, each step annotated with what changes.
// Every chapter opens with a `verdict` — the overall timing chart plotting
// where each voice of that lineage sits relative to the beat (lean in ticks
// @ PPQ 480; `jitter` marks feels that scatter both ways around their lean).
export const CHAPTERS = [
  {
    id: "blues-to-rock",
    title: "Blues → Rock: the flattening",
    blurb: "How the triplet shuffle got hammered flat into straight eighths — and what each generation kept of the swing.",
    intro: "Blues time is triplet time: every beat splits in three, and the whole kit leans deep behind the pulse. Rock is what happened when that shuffle was flattened into straight eighth notes. But the flattening was never total — the best rock drummers kept a memory of the shuffle in the snare's lazy placement, even as punk and metal finally welded everything to the grid.",
    verdict: {
      note: "The story of rock on one axis: the blues snare's +30-tick drag gets squeezed toward zero over twenty-five years, overshoots into punk's forward lean, and finally dies happy on the metal grid. Rudd's +6 is the last audible trace of the shuffle.",
      items: [
        { label: "BLUES SNARE", lean: 30, color: "#E0632F" },
        { label: "PALMER '57", lean: 0, color: "#C9CDD8" },
        { label: "RUDD SNARE", lean: 6, color: "#E0632F" },
        { label: "PUNK (ALL)", lean: -10, color: "#9FB3C8" },
        { label: "METAL GRID", lean: 0, color: "#C9CDD8" },
      ],
    },
    steps: [
      { pattern: "32_slow_blues_shuffle", note: "The source. A full triplet grid, ride swinging, and the snare landing a huge +30ms behind the beat. Nothing is on the grid because the grid isn't the point — the drag IS the feel." },
      { pattern: "33_palmer_lucille", note: "New Orleans, late 1950s. Earl Palmer takes the shuffle and plays it STRAIGHT: even eighth notes, dead on the beat. This is the single most consequential simplification in pop drumming — rock and roll's rhythmic birth certificate." },
      { pattern: "51_watts_honky_tonk", note: "Charlie Watts keeps rock's straight eighths but sneaks the blues back in: he lifts the hi-hat on 2 and 4 so the snare stands alone, and lets it sit a touch late. Loose where Palmer was exact." },
      { pattern: "34_rudd_back_in_black", note: "Phil Rudd industrializes the pocket: machine-even hats, no fills, and a snare that is a consistent whisker late on every single backbeat. The last trace of the shuffle survives as that one tiny, unwavering lag." },
      { pattern: "35_punk_blitzkrieg", note: "Punk flips the lean: everything now pushes AHEAD of the beat (~-10ms), trading the blues drag for urgency. The swing is fully gone; the energy comes from rushing." },
      { pattern: "36_metal_double_kick", note: "The end of the line: 16th-note double kick welded to the grid at 212 bpm, zero swing, zero lean. The blues shuffle has been completely metabolized — precision itself is now the aesthetic." },
    ],
  },
  {
    id: "bonham",
    title: "The Bonham path",
    blurb: "Behind-the-beat weight, kick-drum bursts, and the half-time shuffle conversation between Purdie, Bonham and Porcaro.",
    intro: "John Bonham's signature is weight created by placement: hats locked to the grid while the snare lands fat and late. This chapter walks his three canonical feels, then traces the half-time shuffle conversation — Bernard Purdie invented it, Bonham supersized it, and Jeff Porcaro fused both into Rosanna.",
    verdict: {
      note: "The Bonham tension in one picture: timekeeping locked to the line while the backbeat lands a consistent +10 ticks fat, and the kick bursts push slightly forward. Purdie and Porcaro answer from dead center — their shuffles get the drama from ghosts and dynamics instead of lean.",
      items: [
        { label: "BONHAM HATS", lean: 0, color: "#9FB3C8" },
        { label: "BONHAM SNARE", lean: 10, color: "#E0632F" },
        { label: "KICK BURSTS", lean: -4, color: "#D9AE4A" },
        { label: "PURDIE / PORCARO", lean: 0, color: "#C9CDD8" },
      ],
    },
    steps: [
      { pattern: "01_bonham_levee", note: "The blueprint. Hats dead on the grid, snare +18ms late at maximum velocity, and the famous kick pair on the 'a-of-3'. The tension between locked hats and dragging snare is the whole Bonham sound." },
      { pattern: "03_bonham_good_times", note: "The other side of Bonham: 16th-note kick triplet bursts that PUSH on top of the beat while the snare stays relaxed and back. Two opposing leans inside one kit, one bar." },
      { pattern: "63_purdie_shuffle", note: "Rewind to the source: Bernard Purdie's half-time shuffle (Steely Dan's 'Home at Last'). Triplet grid, a mist of ghost notes on the middle partials, and ONE enormous snare on beat 3, dead center." },
      { pattern: "02_bonham_fool_in_rain", note: "Bonham hears Purdie and answers with 'Fool in the Rain': the same half-time shuffle skeleton, but the big snare on 3 is laid back Bonham-style and the ghosts are softer. Purdie's precision, Bonham's weight." },
      { pattern: "53_porcaro_rosanna", note: "Jeff Porcaro closes the loop, explicitly citing both: 'Rosanna' is the Purdie shuffle's ghost lattice at its densest plus Bonham's half-time architecture, played dead center. The half-time shuffle's final form." },
    ],
  },
  {
    id: "pantheon",
    title: "The Pocket Pantheon",
    blurb: "Six drummers, six answers to the same question: where do you sit against the beat?",
    intro: "Same backbeat, completely different physics. This chapter lines up six giants by the one variable that defines them: placement. Al Jackson Jr. sits deepest of anyone; Ringo and Watts drag by feel; Purdie holds dead center and lets ghosts do the talking; Moon and Copeland attack from in front. There is no correct answer — there is only a committed one.",
    verdict: {
      note: "The whole chapter is this axis. From Al Jackson's +30-tick sag (the deepest pocket ever recorded at Stax) to Copeland's front-edge rim clicks, each drummer picks a spot and never wavers. Note Moon's band — his placement scatters because the surge, not the spot, is his instrument.",
      items: [
        { label: "AL JACKSON SNARE", lean: 30, color: "#E0632F" },
        { label: "RINGO (SWAMP)", lean: 14, color: "#D9AE4A" },
        { label: "WATTS SNARE", lean: 8, color: "#E58BAD" },
        { label: "PURDIE CENTER", lean: 0, color: "#C9CDD8" },
        { label: "COPELAND", lean: -10, color: "#9FB3C8" },
        { label: "MOON (SURGE)", lean: -12, color: "#D64545", jitter: 6 },
      ],
    },
    steps: [
      { pattern: "52_al_jackson_pocket", note: "The deepest pocket: Al Jackson Jr. at Stax. Snare +30ms behind and sparse — he plays fewer notes than anyone and places them later than everyone. Do not decorate." },
      { pattern: "62_rock_steady", note: "Bernard Purdie on 'Rock Steady': accents dead center, wrapped in a mist of ghost notes, with the hat barking as punctuation. Proof that you don't need lean when you have dynamics." },
      { pattern: "50_ringo_come_together", note: "Ringo's swamp: everything behind, and the end-of-bar tom fill dragging progressively later as it goes. Feel over precision — the fill is the signature." },
      { pattern: "51_watts_honky_tonk", note: "Charlie Watts lifts the hat on 2 and 4 so the snare stands alone, a touch late, while the guitar rushes ahead of him. The Stones' wobble is the gap between Watts-behind and Keith-ahead." },
      { pattern: "54_moon_chaos", note: "Keith Moon abandons placement entirely: surging crash-ride chaos ahead of the beat, timekeeping delegated to the bassline. The opposite of Al Jackson in every measurable way." },
      { pattern: "55_copeland_walking", note: "Stewart Copeland attacks from the front edge: rim clicks and splashy hats all leaning early, with reggae-sized space between them. Ahead-of-the-beat as a positive aesthetic, not a mistake." },
    ],
  },
  {
    id: "funk-one",
    title: "Funk: The One",
    blurb: "James Brown puts all the weight on beat one; Sly Stone, Tower of Power and Prince each rebuild funk around it.",
    intro: "Funk reorganized rhythm around The One: beat 1 hit at maximum velocity, everything else orbiting it. From Clyde Stubblefield's crisp authority through Tower of Power's dead-center density to Prince programming The One into a drum machine, this chapter is about how a single accent became a genre.",
    verdict: {
      note: "Funk lives close to the line — its drama is velocity, not lean. Stubblefield rides the front edge, Errico and Garibaldi lock dead center, P-Funk lopes a hair behind to make room for the Moog bass, and the LM-1 is the grid itself. The One is a dynamics event, not a timing one.",
      items: [
        { label: "STUBBLEFIELD", lean: -2, color: "#9FB3C8" },
        { label: "ERRICO LOCK", lean: 0, color: "#D9AE4A" },
        { label: "GARIBALDI", lean: 0, color: "#C9CDD8" },
        { label: "P-FUNK LOPE", lean: 10, color: "#E0632F" },
        { label: "LM-1 GRID", lean: 0, color: "#E58BAD" },
      ],
    },
    steps: [
      { pattern: "42_cold_sweat", note: "Ground zero: Clyde Stubblefield on 'Cold Sweat'. THE ONE — beat-1 kick at maximum velocity — becomes funk's organizing principle. Crisp, on top, alive." },
      { pattern: "44_thank_you_sly", note: "Greg Errico with Sly & the Family Stone: the kick welded to Larry Graham's slap bass, driving instead of leaning. Funk as a rhythm-section handshake." },
      { pattern: "45_what_is_hip", note: "David Garibaldi with Tower of Power: maximum density, dead center. The accents migrate around the bar while the placement never moves a tick — the exact inverse of the lean-based feels." },
      { pattern: "46_flash_light", note: "P-Funk lopes: everything a hair behind, a huge One, and acres of space carved out for Bernie Worrell's Moog bass. The groove breathes where Garibaldi's sprints." },
      { pattern: "47_prince_kiss", note: "Prince closes the arc on an LM-1: bone-dry grid, The One plus silence, and no bass at all. The funk accent survives the total removal of human timing." },
    ],
  },
  {
    id: "new-orleans",
    title: "New Orleans: the Crack",
    blurb: "Bembé, second line, and Zigaboo's offbeats that land in the crack between straight and swung.",
    intro: "New Orleans funk sits in 'the crack' — offbeats placed around +22ms late, in between straight time and shuffle, and allowed to drift. It descends from the bembé bell patterns of the African diaspora through second-line parade drumming into Zigaboo Modeliste's beats with The Meters, which sample so perfectly they became a foundation of hip-hop.",
    verdict: {
      note: "The crack, located: Zigaboo's offbeats sit around +16 ticks — measurably past straight (0) but nowhere near the full shuffle (+38, shown for reference) — and they drift ±5ms around that spot. Downbeats stay anchored. That in-between placement is untranscribable in standard notation, which is exactly why it stayed in New Orleans so long.",
      items: [
        { label: "DOWNBEATS", lean: 0, color: "#D9AE4A" },
        { label: "THE CRACK (OFFBEATS)", lean: 16, color: "#E0632F", jitter: 4 },
        { label: "FULL SHUFFLE (REF)", lean: 38, color: "#9A9077" },
      ],
    },
    steps: [
      { pattern: "28_bembe_bell", note: "The ancestor: the 12/8 bembé bell timeline, with a deliberately ambiguous downbeat. Most Afro-diasporic rhythm — including everything below — descends from this cycle." },
      { pattern: "48_hey_pocky_away", note: "Second line meets funk: Zigaboo's 'Hey Pocky A-Way'. The BIG FOUR — beat-4 kick accented as a launchpad back into the One — is the parade tradition inside a groove." },
      { pattern: "43_cissy_strut", note: "THE crack, canonized: 'Cissy Strut'. Offbeat hats ~+22ms (about 56–58% swing) and drifting ±5ms. Not straight, not shuffled — in between, and alive." },
      { pattern: "49_just_kissed_my_baby", note: "'Just Kissed My Baby': the swampy crack, so internally consistent it loops like a machine — which is why hip-hop producers treated The Meters as a sample library." },
    ],
  },
  {
    id: "afrobeat",
    title: "Tony Allen: Afrobeat",
    blurb: "Bembé roots plus James Brown funk, woven by the one drummer who never plays the same bar twice.",
    intro: "Tony Allen built Afrobeat's drum language for Fela Kuti by fusing the 12/8 bell tradition with James Brown's funk — then refusing the loop. There is no backbeat; there is a continuous ghost-note weave in which one accent, one ghost, one kick migrates every single bar. These grids are snapshots of a feel that is defined by never repeating.",
    verdict: {
      note: "Allen's voices all center on the line but breathe both ways around it — the bands here matter more than the dots. A step sequencer can hold one bar of this; it cannot hold the rule that the next bar must differ. Program four variations and chain them.",
      items: [
        { label: "ACCENTS", lean: 0, color: "#E0632F" },
        { label: "GHOST WEAVE", lean: 0, color: "#9FB3C8", jitter: 10 },
        { label: "KICK CONVERSATION", lean: 0, color: "#D9AE4A", jitter: 8 },
      ],
    },
    steps: [
      { pattern: "28_bembe_bell", note: "The rhythmic ancestor: the 12/8 bembé timeline with its ambiguous downbeat. Afrobeat keeps this cycle's circularity even after flattening onto a 16th grid." },
      { pattern: "42_cold_sweat", note: "The other parent: James Brown's funk, with The One as gravity. Allen heard this and heard a cage — he kept the syncopation and threw away the repetition." },
      { pattern: "37_allen_zombie", note: "'Zombie': no backbeat, a ghost stream with a migrating accent, kicks in conversation with the bass. VARY EVERY BAR — the pattern shown is one frame of a moving picture." },
      { pattern: "38_allen_water", note: "'Water No Get Enemy': the simmer. Half the notes, the same weave, hits loose in both directions. Allen at his quietest is still never identical twice." },
    ],
  },
  {
    id: "questlove",
    title: "The Questlove path",
    blurb: "James Brown → the breakbeat → Dilla's drunk MPC → Questlove playing the machine playing the human.",
    intro: "This is the strangest feedback loop in modern rhythm. Funk drummers played 'human' time; samplers chopped them into loops; J Dilla programmed his MPC to sound drunker than any drummer; and then Questlove — a live drummer — learned to imitate the machine that was imitating drummers. Micro-timing is the entire story here.",
    verdict: {
      note: "The loop in one picture: Stubblefield rides the front edge; Dilla splits the kit — kicks rushing -15 while the snare drags +12 in the same bar; Questlove holds the grid in sample mode; and Pino's bass sags +28 behind everything on Voodoo. The Dilla split and the Pino gap are the two impossible-feeling gestures the whole neo-soul era is built on.",
      items: [
        { label: "STUBBLEFIELD", lean: -2, color: "#9FB3C8" },
        { label: "DILLA KICKS", lean: -15, color: "#D9AE4A", jitter: 4 },
        { label: "DILLA SNARE", lean: 12, color: "#E0632F" },
        { label: "QUESTLOVE GRID", lean: 0, color: "#C9CDD8" },
        { label: "PINO'S BASS", lean: 28, color: "#F5C518" },
      ],
    },
    steps: [
      { pattern: "42_cold_sweat", note: "Ground zero: Clyde Stubblefield with James Brown. 'The One' — beat 1 kick at maximum velocity — becomes funk's organizing principle. Crisp, on top, alive." },
      { pattern: "16_funky_drummer", note: "Stubblefield again, 1970: immaculate 16th hats with whisper swing and ghost notes wrapping the backbeat. The most sampled drum performance in history — the raw material for everything below." },
      { pattern: "04_dilla_fall_in_love", note: "J Dilla, on an MPC with quantize OFF: kicks rush early while the snare drags late IN THE SAME BAR — and the bar repeats identically, which no human would do. 'Drunk' but deliberate." },
      { pattern: "05_dilla_runnin", note: "Dilla's other trick: 58% swing on the hats laid over a dead-straight kick. Two incompatible time-feels running simultaneously. A drummer can't do this; a machine can." },
      { pattern: "06_dilla_didnt_cha_know", note: "The extreme: kicks landing in the cracks BETWEEN 16th positions, unrepresentable on a step grid without micro-offsets. This is what made drummers' jaws drop." },
      { pattern: "39_quest_next_movement", note: "Enter Questlove: 'sample mode'. He flattens his own dynamics and plays with zero bar-to-bar variation so his live kit sounds like a dusty loop. A human imitating a sampler imitating a human." },
      { pattern: "41_quest_chicken_grease", note: "'Drunk mode': Questlove plays Dilla time BY HAND on D'Angelo's Voodoo — kicks cracked early, snare late, a slight wobble per bar. The machine feel, re-humanized." },
      { pattern: "40_quest_voodoo_playa", note: "The Voodoo endgame: Questlove holds the grid while Pino Palladino's bass sags an outrageous 40–50ms behind. The rub between them IS the groove. (Remap the bass track to a bass patch.)" },
    ],
  },
  {
    id: "breaks-to-jungle",
    title: "Breaks → Jungle → UK",
    blurb: "Five sampled bars from 1969–73 become the DNA of hardcore, jungle, drum & bass and garage.",
    intro: "A handful of drum breaks — a few seconds each, sampled from funk 45s — became the rhythmic genome of thirty years of dance music. This chapter plays the canonical breaks in their original feel, then follows what British producers did after pitching them up 30+ bpm: chop them (jungle), re-quantize them (drum & bass), and finally re-swing them (UK garage).",
    verdict: {
      note: "Each break has its own signature lean: the Amen pushes, Think swings its offbeats +19, boom-bap sags +12. The UK continuum then processes those signatures — jungle preserves the Amen's human scatter, drum & bass flattens it to the grid, and garage re-injects swing as a dialed setting rather than a performance.",
      items: [
        { label: "AMEN (ALL)", lean: -3, color: "#9FB3C8", jitter: 3 },
        { label: "THINK OFFBEATS", lean: 19, color: "#E0632F" },
        { label: "BOOM-BAP LEAN", lean: 12, color: "#D9AE4A" },
        { label: "DNB GRID", lean: 0, color: "#C9CDD8" },
        { label: "GARAGE SWING", lean: 31, color: "#E58BAD" },
      ],
    },
    steps: [
      { pattern: "17_amen_break", note: "The Amen: G.C. Coleman's four bars on 'Amen, Brother' (1969). Everything pushes slightly ahead, with the famous displaced snare on the e-of-3. The most sampled recording ever made." },
      { pattern: "18_think_break", note: "The Think break (Lyn Collins, prod. James Brown): crisp economy with swung 16ths. Where the Amen sprawls, Think snaps." },
      { pattern: "19_apache", note: "Apache: a straight, tight kit under a loose bongo layer — two timing systems stacked. Hip-hop's block-party anthem before jungle claimed it." },
      { pattern: "20_impeach_the_president", note: "Impeach the President: the boom-bap lean. Everything sits back, the snare fattest of all. This one seeded hip-hop more than jungle — keep it in your ear for the Producers chapter." },
      { pattern: "14_jungle_amen_chop", note: "Jungle, ~1993: the Amen pitched to 165 bpm and re-chopped. Crucially, the human micro-scatter of the original SURVIVES the sampler — keep the ± offsets or it isn't jungle." },
      { pattern: "15_dnb_twostep", note: "Drum & bass distills jungle's chaos into the two-step: the Amen's anchor points, re-quantized tight at 174. The break is now an idea rather than a recording." },
      { pattern: "13_garage_2step", note: "UK garage closes the loop by putting the swing BACK: a broken kick under 60–66% shuffle. The lean that jungle inherited and drum & bass deleted returns as a knob setting — the swing IS the genre." },
    ],
  },
  {
    id: "producers",
    title: "The Producers path",
    blurb: "How five beatmakers turned the same sampled breaks into five opposite philosophies of time.",
    intro: "Hip-hop production is micro-timing as authorship. Same source breaks, same machines — but Premier, Pete Rock, RZA, Dre, Timbaland and the Neptunes each carved a recognizable signature out of WHERE the hits land. This chapter is a tour of those signatures, ending with the two producers who abandoned the lean entirely.",
    verdict: {
      note: "Five signatures on one axis: Premier and Dre in the classic pocket, Pete Rock deeper in the SP-1200 shuffle, RZA scattered both ways on purpose, and Timbaland/Neptunes at exact zero — the generation that made the grid itself the style. You can identify the producer from the offset alone.",
      items: [
        { label: "PREMIER SNARE", lean: 8, color: "#E0632F" },
        { label: "PETE ROCK", lean: 14, color: "#B8C9A8" },
        { label: "RZA SCATTER", lean: 0, color: "#E58BAD", jitter: 14 },
        { label: "DRE POCKET", lean: 8, color: "#D9AE4A" },
        { label: "TIMBALAND / NEPTUNES", lean: 0, color: "#C9CDD8" },
      ],
    },
    steps: [
      { pattern: "20_impeach_the_president", note: "The raw material: the boom-bap lean, everything behind, snare fattest. Every producer below is reacting to this feel." },
      { pattern: "21_premier_ny_state", note: "DJ Premier: tight MPC swing, snare like a slammed door — the hits sit just behind (+6–12 ticks), the classic pocket. New York austerity." },
      { pattern: "23_pete_rock_troy", note: "Pete Rock: the SP-1200's heavy shuffle (61% swing), dusty and laid back. Where Premier is a straight line, Pete Rock is a slouch." },
      { pattern: "24_rza_cream", note: "RZA: unquantized scatter in BOTH directions. It sounds broken and that's the point — do not clean it up. Wu-Tang's menace lives in the wobble." },
      { pattern: "22_dre_g_thang", note: "Dr. Dre: G-funk replaces dust with live-pocket sheen — sparse hits, everything a consistent hair behind, room for the synth bass. West-coast answer to the East-coast lean." },
      { pattern: "25_timbaland_ays", note: "Timbaland breaks the whole paradigm: grid-PERFECT placement, funk generated by stuttered kick patterns and silence instead of lean. Half-time snare. The future arrives quantized." },
      { pattern: "26_neptunes_grindin", note: "The Neptunes take it to zero: 'Grindin'' is minimalism as aggression — clap, kick, rim and negative space, nothing off-grid. Micro-timing's role is over; arrangement is the new groove." },
    ],
  },
  {
    id: "kingston",
    title: "Kingston: One Drop → Dancehall",
    blurb: "Carlton Barrett empties beat one; Sly & Robbie militarize it, then digitize it — and the bass always sags behind.",
    intro: "Reggae is built on an absence: beat one, the loudest beat in Western pop, is left EMPTY, and the weight lands on beat 3. From Carlton Barrett's one drop through Sly Dunbar's rockers to digital dancehall, the drums get progressively tighter — while Robbie Shakespeare's bass keeps sagging 25–40ms behind them. The gap between drums and bass is the sound of Jamaica.",
    verdict: {
      note: "Two men, one elastic: Sly drums militant — crisp, on top, forever modernizing — while Robbie's bass arrives +24 ticks late, each note like it had to be talked into it. The daylight between them is the Riddim Twins' actual instrument. Barrett's beat-3 drop sits in between; the digital era finally quantizes the gap but keeps its ghost in the arrangement.",
      items: [
        { label: "SLY — ON TOP", lean: -2, color: "#E0632F" },
        { label: "BARRETT'S 3", lean: 12, color: "#E58BAD" },
        { label: "ROBBIE'S BASS", lean: 24, color: "#F5C518" },
        { label: "DANCEHALL GRID", lean: 0, color: "#C9CDD8" },
      ],
    },
    steps: [
      { pattern: "07_barrett_one_drop", note: "Carlton Barrett with the Wailers: the one drop. Beat 1 empty, kick and rim landing TOGETHER on 3, fat and late, hats gently swung. Gravity relocated." },
      { pattern: "08_barrett_get_up_stand_up", note: "The one drop with vocabulary: rim-click ghosts and a kick pickup that leans INTO the still-empty beat 1. The silence gets framed harder." },
      { pattern: "09_barrett_steppers", note: "Steppers: Barrett fills the floor — kick on all four, everything marginally behind. Militant, but still reggae because the whole kit leans back together." },
      { pattern: "64_right_time_rockers", note: "Sly Dunbar's rockers: the militant four made surgical, while Robbie Shakespeare's BASS sags a colossal 40ms behind the kit. Listen to the gap — the gap is the sound. (Remap the bass track.)" },
      { pattern: "65_sponji_reggae", note: "The syndrum era: electronic tom accents enter, drums tighten toward the grid, and the bass sags even DEEPER in contrast. Man vs machine inside one rhythm section." },
      { pattern: "66_pull_up_bumper", note: "Compass Point, Grace Jones: near-grid drums under a busy bass that still lives +25ms back. Sly & Robbie sell Jamaican time to the international pop chart." },
      { pattern: "67_murder_she_wrote", note: "Digital dancehall: the tresillo (3+3+2) snare, everything quantized — but the bassline still carries Robbie-shaped DNA. From here the tresillo conquers the world…" },
      { pattern: "31_dembow", note: "…as dembow. The dancehall tresillo dropped onto a quantized four-on-floor kick becomes reggaeton's engine — the most globally dominant rhythm of the 21st century." },
    ],
  },
  {
    id: "latin",
    title: "Latin: the Clave Line",
    blurb: "From the bembé timeline to son clave, samba's early 16ths, bossa's hammock, and dembow's world conquest.",
    intro: "Afro-Latin rhythm is organized by timelines — asymmetric key patterns (bembé, clave, tresillo) that everything else locks to. This chapter follows the line from the 12/8 ancestor through Cuban son clave and Brazil's two opposite answers (samba rushing, bossa relaxing), to the tresillo's final form as reggaeton's dembow.",
    verdict: {
      note: "Latin feels split around the line, not behind it: the samba caixa places its middle 16ths EARLY (-12) for that forward tumble, clave and cascara ride on top, bossa lets the whole picture sag a gentle +2, and dembow is quantized flat. The lean tells you the country.",
      items: [
        { label: "SAMBA CAIXA 16THS", lean: -12, color: "#E0632F" },
        { label: "CLAVE / CASCARA", lean: -2, color: "#E58BAD" },
        { label: "BOSSA (ALL)", lean: 2, color: "#C9CDD8" },
        { label: "DEMBOW GRID", lean: 0, color: "#D9AE4A" },
      ],
    },
    steps: [
      { pattern: "28_bembe_bell", note: "The ancestor: the 12/8 bembé bell with a deliberately ambiguous downbeat. Squeeze this cycle onto a straight grid and you get the clave family." },
      { pattern: "27_son_clave_salsa", note: "3-2 son clave with the salsa kit around it: clave on the rim, cascara on the ride, conga slap and open tones — everything on top of the beat while the bass anticipates. Two bars because the pattern IS asymmetry." },
      { pattern: "29_samba_batucada", note: "Brazil accelerates: the caixa's 2nd and 3rd 16ths land EARLY (-12ms), creating samba's forward tumble, while the surdo puts the weight on 2 and 4. The only groove in the atlas built on rushing." },
      { pattern: "30_bossa_nova", note: "Then Brazil relaxes: bossa nova is samba in a hammock — same skeleton, everything +4ms, played at a whisper. The same DNA at two opposite energies." },
      { pattern: "31_dembow", note: "The tresillo endgame: dancehall's 3+3+2 snare on a quantized four-on-floor. Dembow closes the loop begun by the bembé bell — the timeline is now the whole song." },
    ],
  },
  {
    id: "four-on-floor",
    title: "Four-on-the-floor: 1938 → Techno",
    blurb: "From Papa Jo Jones feathering the kick to the machine grid — one pattern, ninety years.",
    intro: "Kick on every beat is the oldest trick in dance music, but its meaning keeps changing: felt-not-heard in swing, stomped in Motown, silked in disco, and finally welded to a machine grid in house and techno — where the humanity migrates into swing settings, velocity ramps, and one drowsy shaker.",
    verdict: {
      note: "Same kick pattern, ninety years of placement: Papa Jo feathers it just behind, Motown stomps it forward, Earl Young silks it back, house locks it to zero — and then deep house hangs a shaker +24 over the rigid floor. When the floor stopped moving, the lean moved upstairs.",
      items: [
        { label: "PAPA JO FEATHER", lean: 3, color: "#D9AE4A" },
        { label: "MOTOWN STOMP", lean: -8, color: "#E0632F" },
        { label: "DISCO (EARL YOUNG)", lean: 6, color: "#B8C9A8" },
        { label: "HOUSE / TECHNO GRID", lean: 0, color: "#C9CDD8" },
        { label: "DEEP HOUSE SHAKER", lean: 24, color: "#A0C8B8" },
      ],
    },
    steps: [
      { pattern: "56_feathered_four", note: "Papa Jo Jones, 1938: the four is FEATHERED — kick at velocity ~25, felt not heard, under a swinging ride. Dance music's foundation, played at a whisper." },
      { pattern: "57_motown_stomp", note: "Motown turns the four into a fist: kick, snare AND tambourine on every beat, leaning forward. The four is now the hook itself." },
      { pattern: "58_disco_earl_young", note: "Earl Young invents disco drumming: the four with open-hat exhales on the offbeats, swung 16ths, everything sitting back a touch. Live silk — the direct template for house." },
      { pattern: "10_house_classic", note: "House: a drum machine plays Earl Young. The open-hat offbeat survives, the swing is now a knob (55%), the placement is perfect. Chicago turns a feel into a spec." },
      { pattern: "59_deep_house", note: "Deep house re-humanizes the machine from the top down: rigid kick floor, but the shaker drags HARD (60% swing) like a drowsy ceiling over the grid." },
      { pattern: "60_filter_house_pump", note: "Filter house: groove generated by DYNAMICS alone — hat velocity ramps 30→105 inside each beat, faking a sidechain pump. No timing tricks at all." },
      { pattern: "11_techno", note: "Techno: zero swing, zero lean, zero apology. The grid itself becomes the aesthetic object. What was a limitation is now the entire point." },
      { pattern: "12_trance", note: "Trance strips even the funk of silence away: a blank metronome where all motion belongs to the offbeat bassline. The four as pure carrier wave." },
      { pattern: "61_dance_punk", note: "Coda: DFA's dance-punk plays disco's four with punk's clenched-teeth FORWARD lean — proof the pattern is a canvas and the lean is the paint." },
    ],
  },
];
