// Curated listening paths through the atlas. Each step pairs a pattern id
// with a note explaining what changes at that point in the lineage.
export const PATHS = [
  {
    id: "blues-to-rock",
    title: "Blues → Rock: the flattening",
    blurb: "How the triplet shuffle got hammered flat into straight eighths — and what each generation kept of the swing.",
    intro: "Blues time is triplet time: every beat splits in three, and the whole kit leans deep behind the pulse. Rock is what happened when that shuffle was flattened into straight eighth notes. But the flattening was never total — the best rock drummers kept a memory of the shuffle in the snare's lazy placement, even as punk and metal finally welded everything to the grid.",
    steps: [
      { pattern: "32_slow_blues_shuffle", note: "The source. A full triplet grid, ride swinging, and the snare landing a huge +30ms behind the beat. Nothing is on the grid because the grid isn't the point — the drag IS the feel." },
      { pattern: "33_palmer_lucille", note: "New Orleans, late 1950s. Earl Palmer takes the shuffle and plays it STRAIGHT: even eighth notes, dead on the beat. This is the single most consequential simplification in pop drumming — rock and roll's rhythmic birth certificate." },
      { pattern: "51_watts_honky_tonk", note: "Charlie Watts keeps rock's straight eighths but sneaks the blues back in: he lifts the hi-hat on 2 and 4 so the snare stands alone, and lets it sit a touch late. Loose where Palmer was exact." },
      { pattern: "34_rudd_back_in_black", note: "Phil Rudd industrializes the pocket: machine-even hats, no fills, and a snare that is a consistent whisker late on every single backbeat. The last trace of the shuffle survives as that one tiny, unwavering lag." },
      { pattern: "35_punk_blitzkrieg", note: "Punk flips the lean: everything now pushes AHEAD of the beat (~-10ms), trading the blues drag for urgency. The swing is fully gone; the energy comes from rushing." },
      { pattern: "36_metal_double_kick", note: "The end of the line: 16th-note double kick welded to the grid at 212 bpm, zero swing, zero lean. The blues shuffle has been completely metabolized — precision itself is now the aesthetic." },
    ],
  },
  {
    id: "bonham",
    title: "The Bonham path",
    blurb: "Behind-the-beat weight, kick-drum bursts, and the half-time shuffle conversation between Purdie, Bonham and Porcaro.",
    intro: "John Bonham's signature is weight created by placement: hats locked to the grid while the snare lands fat and late. This path walks his three canonical feels, then traces the half-time shuffle conversation — Bernard Purdie invented it, Bonham supersized it, and Jeff Porcaro fused both into Rosanna.",
    steps: [
      { pattern: "01_bonham_levee", note: "The blueprint. Hats dead on the grid, snare +18ms late at maximum velocity, and the famous kick pair on the 'a-of-3'. The tension between locked hats and dragging snare is the whole Bonham sound." },
      { pattern: "03_bonham_good_times", note: "The other side of Bonham: 16th-note kick triplet bursts that PUSH on top of the beat while the snare stays relaxed and back. Two opposing leans inside one kit, one bar." },
      { pattern: "63_purdie_shuffle", note: "Rewind to the source: Bernard Purdie's half-time shuffle (Steely Dan's 'Home at Last'). Triplet grid, a mist of ghost notes on the middle partials, and ONE enormous snare on beat 3, dead center." },
      { pattern: "02_bonham_fool_in_rain", note: "Bonham hears Purdie and answers with 'Fool in the Rain': the same half-time shuffle skeleton, but the big snare on 3 is laid back Bonham-style and the ghosts are softer. Purdie's precision, Bonham's weight." },
      { pattern: "53_porcaro_rosanna", note: "Jeff Porcaro closes the loop, explicitly citing both: 'Rosanna' is the Purdie shuffle's ghost lattice at its densest plus Bonham's half-time architecture, played dead center. The half-time shuffle's final form." },
    ],
  },
  {
    id: "questlove",
    title: "The Questlove path",
    blurb: "James Brown → the breakbeat → Dilla's drunk MPC → Questlove playing the machine playing the human.",
    intro: "This is the strangest feedback loop in modern rhythm. Funk drummers played 'human' time; samplers chopped them into loops; J Dilla programmed his MPC to sound drunker than any drummer; and then Questlove — a live drummer — learned to imitate the machine that was imitating drummers. Micro-timing is the entire story here.",
    steps: [
      { pattern: "42_cold_sweat", note: "Ground zero: Clyde Stubblefield with James Brown. 'The One' — beat 1 kick at maximum velocity — becomes funk's organizing principle. Crisp, on top, alive." },
      { pattern: "16_funky_drummer", note: "Stubblefield again, 1970: immaculate 16th hats with whisper swing and ghost notes wrapping the backbeat. The most sampled drum performance in history — the raw material for everything below." },
      { pattern: "04_dilla_fall_in_love", note: "J Dilla, on an MPC with quantize OFF: kicks rush early while the snare drags late IN THE SAME BAR — and the bar repeats identically, which no human would do. 'Drunk' but deliberate." },
      { pattern: "05_dilla_runnin", note: "Dilla's other trick: 58% swing on the hats laid over a dead-straight kick. Two incompatible time-feels running simultaneously. A drummer can't do this; a machine can." },
      { pattern: "06_dilla_didnt_cha_know", note: "The extreme: kicks landing in the cracks BETWEEN 16th positions, unrepresentable on a step grid without micro-offsets. This is what made drummers' jaws drop." },
      { pattern: "39_quest_next_movement", note: "Enter Questlove: 'sample mode'. He flattens his own dynamics and plays with zero bar-to-bar variation so his live kit sounds like a dusty loop. A human imitating a sampler imitating a human." },
      { pattern: "41_quest_chicken_grease", note: "'Drunk mode': Questlove plays Dilla time BY HAND on D'Angelo's Voodoo — kicks cracked early, snare late, a slight wobble per bar. The machine feel, re-humanized." },
      { pattern: "40_quest_voodoo_playa", note: "The Voodoo endgame: Questlove holds the grid while Pino Palladino's bass sags an outrageous 40–50ms behind. The rub between them IS the groove. (Remap the bass track to a bass patch.)" },
    ],
  },
  {
    id: "breaks-to-jungle",
    title: "Breaks → Jungle → Drum & Bass",
    blurb: "Five sampled bars from 1969–73 become the DNA of hardcore, jungle and DnB.",
    intro: "A handful of drum breaks — a few seconds each, sampled from funk 45s — became the rhythmic genome of thirty years of dance music. This path plays the canonical breaks in their original feel, then shows what happened when British producers pitched them up 30+ bpm and re-chopped them.",
    steps: [
      { pattern: "17_amen_break", note: "The Amen: G.C. Coleman's four bars on 'Amen, Brother' (1969). Everything pushes slightly ahead, with the famous displaced snare on the e-of-3. The most sampled recording ever made." },
      { pattern: "18_think_break", note: "The Think break (Lyn Collins, prod. James Brown): crisp economy with swung 16ths. Where the Amen sprawls, Think snaps." },
      { pattern: "19_apache", note: "Apache: a straight, tight kit under a loose bongo layer — two timing systems stacked. Hip-hop's block-party anthem before jungle claimed it." },
      { pattern: "20_impeach_the_president", note: "Impeach the President: the boom-bap lean. Everything sits back, the snare fattest of all. This one seeded hip-hop more than jungle — keep it in your ear for the Producers path." },
      { pattern: "14_jungle_amen_chop", note: "Jungle, ~1993: the Amen pitched to 165 bpm and re-chopped. Crucially, the human micro-scatter of the original SURVIVES the sampler — keep the ± offsets or it isn't jungle." },
      { pattern: "15_dnb_twostep", note: "Drum & bass distills jungle's chaos into the two-step: the Amen's anchor points, re-quantized tight at 174. The break is now an idea rather than a recording." },
    ],
  },
  {
    id: "producers",
    title: "The Producers path",
    blurb: "How five beatmakers turned the same sampled breaks into five opposite philosophies of time.",
    intro: "Hip-hop production is micro-timing as authorship. Same source breaks, same machines — but Premier, Pete Rock, RZA, Dre, Timbaland and the Neptunes each carved a recognizable signature out of WHERE the hits land. This path is a tour of those signatures, ending with the two producers who abandoned the lean entirely.",
    steps: [
      { pattern: "20_impeach_the_president", note: "The raw material: the boom-bap lean, everything behind, snare fattest. Every producer below is reacting to this feel." },
      { pattern: "21_premier_ny_state", note: "DJ Premier: tight MPC swing, snare like a slammed door — the hits sit just behind (+6–12 ticks), the classic pocket. New York austerity." },
      { pattern: "23_pete_rock_troy", note: "Pete Rock: the SP-1200's heavy shuffle (61% swing), dusty and laid back. Where Premier is a straight line, Pete Rock is a slouch." },
      { pattern: "24_rza_cream", note: "RZA: unquantized scatter in BOTH directions. It sounds broken and that's the point — do not clean it up. Wu-Tang's menace lives in the wobble." },
      { pattern: "22_dre_g_thang", note: "Dr. Dre: G-funk replaces dust with live-pocket sheen — sparse hits, everything a consistent hair behind, room for the synth bass. West-coast answer to the East-coast lean." },
      { pattern: "25_timbaland_ays", note: "Timbaland breaks the whole paradigm: grid-PERFECT placement, funk generated by stuttered kick patterns and silence instead of lean. Half-time snare. The future arrives quantized." },
      { pattern: "26_neptunes_grindin", note: "The Neptunes take it to zero: 'Grindin'' is minimalism as aggression — clap, kick, rim and negative space, nothing off-grid. Micro-timing's role is over; arrangement is the new groove." },
    ],
  },
  {
    id: "kingston",
    title: "Kingston: One Drop → Dancehall",
    blurb: "Carlton Barrett empties beat one; Sly & Robbie militarize it, then digitize it — and the bass always sags behind.",
    intro: "Reggae is built on an absence: beat one, the loudest beat in Western pop, is left EMPTY, and the weight lands on beat 3. From Carlton Barrett's one drop through Sly Dunbar's rockers to digital dancehall, the drums get progressively tighter — while Robbie Shakespeare's bass keeps sagging 25–40ms behind them. The gap between drums and bass is the sound of Jamaica.",
    steps: [
      { pattern: "07_barrett_one_drop", note: "Carlton Barrett with the Wailers: the one drop. Beat 1 empty, kick and rim landing TOGETHER on 3, fat and late, hats gently swung. Gravity relocated." },
      { pattern: "08_barrett_get_up_stand_up", note: "The one drop with vocabulary: rim-click ghosts and a kick pickup that leans INTO the still-empty beat 1. The silence gets framed harder." },
      { pattern: "09_barrett_steppers", note: "Steppers: Barrett fills the floor — kick on all four, everything marginally behind. Militant, but still reggae because the whole kit leans back together." },
      { pattern: "64_right_time_rockers", note: "Sly Dunbar's rockers: the militant four made surgical, while Robbie Shakespeare's BASS sags a colossal 40ms behind the kit. Listen to the gap — the gap is the sound. (Remap the bass track.)" },
      { pattern: "65_sponji_reggae", note: "The syndrum era: electronic tom accents enter, drums tighten toward the grid, and the bass sags even DEEPER in contrast. Man vs machine inside one rhythm section." },
      { pattern: "66_pull_up_bumper", note: "Compass Point, Grace Jones: near-grid drums under a busy bass that still lives +25ms back. Sly & Robbie sell Jamaican time to the international pop chart." },
      { pattern: "67_murder_she_wrote", note: "Digital dancehall: the tresillo (3+3+2) snare, everything quantized — but the bassline still carries Robbie-shaped DNA. From here the tresillo conquers the world…" },
      { pattern: "31_dembow", note: "…as dembow. The dancehall tresillo dropped onto a quantized four-on-floor kick becomes reggaeton's engine — the most globally dominant rhythm of the 21st century." },
    ],
  },
  {
    id: "four-on-floor",
    title: "Four-on-the-floor: 1938 → Techno",
    blurb: "From Papa Jo Jones feathering the kick to the machine grid — one pattern, ninety years.",
    intro: "Kick on every beat is the oldest trick in dance music, but its meaning keeps changing: felt-not-heard in swing, stomped in Motown, silked in disco, and finally welded to a machine grid in house and techno — where the humanity migrates into swing settings, velocity ramps, and one drowsy shaker.",
    steps: [
      { pattern: "56_feathered_four", note: "Papa Jo Jones, 1938: the four is FEATHERED — kick at velocity ~25, felt not heard, under a swinging ride. Dance music's foundation, played at a whisper." },
      { pattern: "57_motown_stomp", note: "Motown turns the four into a fist: kick, snare AND tambourine on every beat, leaning forward. The four is now the hook itself." },
      { pattern: "58_disco_earl_young", note: "Earl Young invents disco drumming: the four with open-hat exhales on the offbeats, swung 16ths, everything sitting back a touch. Live silk — the direct template for house." },
      { pattern: "10_house_classic", note: "House: a drum machine plays Earl Young. The open-hat offbeat survives, the swing is now a knob (55%), the placement is perfect. Chicago turns a feel into a spec." },
      { pattern: "59_deep_house", note: "Deep house re-humanizes the machine from the top down: rigid kick floor, but the shaker drags HARD (60% swing) like a drowsy ceiling over the grid." },
      { pattern: "60_filter_house_pump", note: "Filter house: groove generated by DYNAMICS alone — hat velocity ramps 30→105 inside each beat, faking a sidechain pump. No timing tricks at all." },
      { pattern: "11_techno", note: "Techno: zero swing, zero lean, zero apology. The grid itself becomes the aesthetic object. What was a limitation is now the entire point." },
      { pattern: "12_trance", note: "Trance strips even the funk of silence away: a blank metronome where all motion belongs to the offbeat bassline. The four as pure carrier wave." },
      { pattern: "61_dance_punk", note: "Coda: DFA's dance-punk plays disco's four with punk's clenched-teeth FORWARD lean — proof the pattern is a canvas and the lean is the paint." },
    ],
  },
  {
    id: "new-orleans",
    title: "New Orleans: the Crack",
    blurb: "Bembé, second line, and Zigaboo's offbeats that land in the crack between straight and swung.",
    intro: "New Orleans funk sits in 'the crack' — offbeats placed around +22ms late, in between straight time and shuffle, and allowed to drift. It descends from the bembé bell patterns of the African diaspora through second-line parade drumming into Zigaboo Modeliste's beats with The Meters, which sample so perfectly they became a foundation of hip-hop.",
    steps: [
      { pattern: "28_bembe_bell", note: "The ancestor: the 12/8 bembé bell timeline, with a deliberately ambiguous downbeat. Most Afro-diasporic rhythm — including everything below — descends from this cycle." },
      { pattern: "48_hey_pocky_away", note: "Second line meets funk: Zigaboo's 'Hey Pocky A-Way'. The BIG FOUR — beat-4 kick accented as a launchpad back into the One — is the parade tradition inside a groove." },
      { pattern: "43_cissy_strut", note: "THE crack, canonized: 'Cissy Strut'. Offbeat hats ~+22ms (about 56–58% swing) and drifting ±5ms. Not straight, not shuffled — in between, and alive." },
      { pattern: "49_just_kissed_my_baby", note: "'Just Kissed My Baby': the swampy crack, so internally consistent it loops like a machine — which is why hip-hop producers treated The Meters as a sample library." },
    ],
  },
];
